# Generated by Django 5.2.1 on 2025-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorseResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datum', models.IntegerField(db_column='datum')),
                ('bankod', models.CharField(db_column='bankod', max_length=20)),
                ('lopp', models.IntegerField(db_column='lopp')),
                ('nr', models.IntegerField(db_column='nr')),
                ('namn', models.CharField(db_column='namn', max_length=50)),
                ('distans', models.IntegerField(blank=True, db_column='distans', null=True)),
                ('tillagg', models.IntegerField(blank=True, db_column='tillagg', null=True)),
                ('spar', models.IntegerField(blank=True, db_column='spar', null=True)),
                ('placering', models.IntegerField(blank=True, db_column='placering', null=True)),
                ('tid', models.FloatField(blank=True, db_column='tid', null=True)),
                ('startmetod', models.CharField(blank=True, db_column='startmetod', max_length=1)),
                ('galopp', models.CharField(blank=True, db_column='galopp', max_length=1)),
                ('underlag', models.CharField(blank=True, db_column='underlag', max_length=2)),
                ('ny_tid', models.FloatField(blank=True, db_column='nytid', null=True)),
                ('diff_tid', models.FloatField(blank=True, db_column='difftid', null=True)),
                ('diff_vinst', models.FloatField(blank=True, db_column='diffvinst', null=True)),
                ('diff_medel', models.FloatField(blank=True, db_column='diffmedel', null=True)),
                ('sortering', models.IntegerField(blank=True, db_column='sortering', null=True)),
                ('pris', models.IntegerField(blank=True, db_column='pris', null=True)),
                ('tillagg_tid', models.FloatField(blank=True, db_column='tillaggtid', null=True)),
                ('lopp_tid', models.FloatField(blank=True, db_column='lopptid', null=True)),
                ('sortering_plac', models.IntegerField(blank=True, db_column='sorteringplac', null=True)),
                ('sortering_tid', models.IntegerField(blank=True, db_column='sorteringtid', null=True)),
                ('sortering_pris', models.IntegerField(blank=True, db_column='sorteringpris', null=True)),
                ('sortering_klass', models.IntegerField(blank=True, db_column='sorteringklass', null=True)),
                ('lopp_klass', models.FloatField(blank=True, db_column='loppklass', null=True)),
                ('odds', models.IntegerField(db_column='odds', default=999)),
                ('kusk', models.CharField(blank=True, db_column='kusk', default='', max_length=80)),
            ],
            options={
                'db_table': 'resultat',
                'ordering': ('datum', 'bankod', 'lopp', 'placering'),
                'constraints': [models.UniqueConstraint(fields=('datum', 'bankod', 'lopp', 'namn'), name='uq_resultat_datum_bankod_lopp_namn')],
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startdatum', models.IntegerField(db_column='startdatum')),
                ('bankod', models.CharField(db_column='bankod', max_length=2)),
                ('namn', models.CharField(db_column='namn', max_length=50)),
                ('proposition', models.IntegerField(db_column='proposition')),
                ('distans', models.IntegerField(blank=True, db_column='distans', null=True)),
                ('kuskanskemal', models.CharField(blank=True, db_column='kuskanskemal', max_length=120, null=True)),
            ],
            options={
                'db_table': 'proposition',
                'ordering': ('startdatum', 'bankod', 'proposition', 'namn'),
                'unique_together': {('startdatum', 'bankod', 'namn', 'proposition')},
            },
        ),
        migrations.CreateModel(
            name='StartList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startdatum', models.IntegerField(db_column='startdatum')),
                ('bankod', models.CharField(db_column='bankod', max_length=2)),
                ('lopp', models.IntegerField(db_column='lopp')),
                ('nr', models.IntegerField(db_column='nr')),
                ('namn', models.CharField(db_column='namn', max_length=50)),
                ('spar', models.IntegerField(blank=True, db_column='spar', null=True)),
                ('distans', models.IntegerField(blank=True, db_column='distans', null=True)),
                ('kusk', models.CharField(db_column='kusk', max_length=120)),
            ],
            options={
                'db_table': 'startlista',
                'ordering': ('startdatum', 'bankod', 'lopp', 'nr'),
                'unique_together': {('startdatum', 'bankod', 'lopp', 'nr')},
            },
        ),
    ]
