# Generated by Django 5.2.1 on 2025-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorseResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datum', models.IntegerField(db_column='Datum')),
                ('bankod', models.CharField(db_column='Bankod', max_length=2)),
                ('lopp', models.IntegerField(db_column='Lopp')),
                ('nr', models.IntegerField(db_column='Nr')),
                ('namn', models.CharField(db_column='Namn', max_length=50)),
                ('distans', models.IntegerField(blank=True, db_column='Distans', null=True)),
                ('tillagg', models.IntegerField(blank=True, db_column='Tillagg', null=True)),
                ('spar', models.IntegerField(blank=True, db_column='Spar', null=True)),
                ('placering', models.IntegerField(blank=True, db_column='Placering', null=True)),
                ('tid', models.FloatField(blank=True, db_column='Tid', null=True)),
                ('startmetod', models.CharField(blank=True, db_column='Startmetod', max_length=1)),
                ('galopp', models.CharField(blank=True, db_column='Galopp', max_length=1)),
                ('underlag', models.CharField(blank=True, db_column='Underlag', max_length=1)),
                ('ny_tid', models.FloatField(blank=True, db_column='NyTid', null=True)),
                ('diff_tid', models.FloatField(blank=True, db_column='DiffTid', null=True)),
                ('diff_vinst', models.FloatField(blank=True, db_column='DiffVinst', null=True)),
                ('diff_medel', models.FloatField(blank=True, db_column='DiffMedel', null=True)),
                ('sortering', models.IntegerField(blank=True, db_column='Sortering', null=True)),
                ('pris', models.IntegerField(blank=True, db_column='Pris', null=True)),
                ('tillagg_tid', models.FloatField(blank=True, db_column='TillaggTid', null=True)),
                ('lopp_tid', models.FloatField(blank=True, db_column='LoppTid', null=True)),
                ('sortering_plac', models.IntegerField(blank=True, db_column='SorteringPlac', null=True)),
                ('sortering_tid', models.IntegerField(blank=True, db_column='SorteringTid', null=True)),
                ('sortering_pris', models.IntegerField(blank=True, db_column='SorteringPris', null=True)),
                ('sortering_klass', models.IntegerField(blank=True, db_column='SorteringKlass', null=True)),
                ('lopp_klass', models.FloatField(blank=True, db_column='LoppKlass', null=True)),
            ],
            options={
                'db_table': 'Resultat',
                'ordering': ('datum', 'lopp', 'placering'),
                'unique_together': {('datum', 'lopp', 'nr')},
            },
        ),
    ]
