# Generated by Django 5.2.1 on 2025-06-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horseresult',
            options={'ordering': ('datum', 'bankod', 'lopp', 'placering')},
        ),
        migrations.AlterUniqueTogether(
            name='horseresult',
            unique_together={('datum', 'bankod', 'lopp', 'nr')},
        ),
    ]
