# Generated by Django 5.2.1 on 2025-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_horseresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startdatum', models.IntegerField(db_column='Startdatum')),
                ('bankod', models.CharField(db_column='Bankod', max_length=2)),
                ('lopp', models.IntegerField(db_column='Lopp')),
                ('nr', models.IntegerField(db_column='Nr')),
                ('namn', models.CharField(db_column='Namn', max_length=50)),
                ('spar', models.IntegerField(blank=True, db_column='Spar', null=True)),
                ('distans', models.IntegerField(blank=True, db_column='Distans', null=True)),
                ('kusk', models.CharField(db_column='Kusk', max_length=120)),
            ],
            options={
                'db_table': 'Startlista',
                'ordering': ('startdatum', 'bankod', 'lopp', 'nr'),
                'unique_together': {('startdatum', 'bankod', 'lopp', 'nr')},
            },
        ),
    ]
